language: swift
os: osx
osx_image: xcode11.3
script: xcodebuild -project CodePad.xcodeproj -scheme CodePad -destination platform\=iOS\ Simulator,OS\=13.3,name\=iPhone\ 8 -testPlan "CI Test Plan" build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
